### PR TITLE
Send CORS headers in simple mode

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by mdhiggins** [comment]
What benefit does the CORS header have for the simple output?

**Comment by scop** [comment]
Enables using the blaster API from a browser app hosted on another URL/site/server (not on the device). See e.g. https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by mdhiggins** [comment]
I read over that, it seems like the CORS headers would be beneficial with the default pages but not as useful for the simple pages. The default pages use bootstrap which does pull its CSS sources from a different location but the simple pages shouldn't have any cross referencing that would require this header
Am I mistaken in my understanding?

**Comment by scop** [comment]
I don't think there's any real use for CORS headers on the default pages, unless you want to promote accessing them using a XmlHttpRequest from a web app hosted somewhere else. I don't think that should be done because there is the simple interface which is a perfect fit for that kind of an access pattern. CORS has nothing really to do with the CSS you use with the default pages. It just enables people to write web apps that are distributed from somewhere else to access the simple interface on this device using ajax requests.

**Comment by scop** [comment]
Rebased against current master.

**Comment by scop** [comment]
Rebased against current master again.

**Comment by scop** [comment]
Thanks!

**Pull request merged**
